services:
  producer:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gtfsrt-twisto
    env_file:
      - path: .env
        required: false
    environment:
      - TZ=Europe/Paris
    ports:
      - "127.0.0.1:50020:3000"
    restart: unless-stopped
